### ISSUE TITLE
[Rose-Pine] Checkboxes not displaying as checked

### ISSUE THREAD

**Issue by sigrunixia** [kepano/obsidian-minimal-publish#2]
Hello hello!

Looks like there is some contrast help needed on checkboxes and showing toggled status.
![CleanShot 2024-02-01 at 15 54 46](https://github.com/kepano/obsidian-minimal-publish/assets/68425372/8f95842a-094e-4215-bea4-8993b9aab43f)
Above is a screenshot of Rose Pine on desktop.

![CleanShot 2024-02-01 at 15 56 08](https://github.com/kepano/obsidian-minimal-publish/assets/68425372/03fcb77d-45bf-48e2-a319-d68571dbcd73)
This is the same area on Publish. 

![CleanShot 2024-02-01 at 16 05 18](https://github.com/kepano/obsidian-minimal-publish/assets/68425372/24dfae36-b4d2-4a27-bfd4-3350dc5530f6)
This is the same area on Publish with default theme and no additional CSS.

Looking closer, it seems the subtraction of the `--ax` variables in the Publish version of rose is a cause. 

My testing environment(s):
**macOS Sonoma 14.3**
Safari 17.3
Arc 1.27.3

Submitting PR to fix.

**Comment by kepano** [comment]
Thanks!!
