### ISSUE TITLE
updating Obsidian Minimal Publish

### ISSUE THREAD

**Issue by nodegraphics** [kepano/obsidian-minimal-publish#7]
Hello, 
i was wondering if obsidian minimal publish gets updated with obsidian itself ? if not, do i make a clean install again to update with the latest version ?

**Comment by kepano** [comment]
No there is no update mechanism for Publish themes. You have to get the latest version and re-publish it.

https://minimal.guide/publish/download

**Comment by nodegraphics** [comment]
Thank you
